apiVersion: v1
kind: Service
metadata:
  name: my-app-service # Choose a name for your service
spec:
  type: NodePort
  selector:
    app: my-app # This must match the labels of your application's pods
  ports:
    - protocol: TCP
      port: 80 # The port the service itself is exposed on *within the cluster*
      targetPort: 8080 # The port your application pod is listening on
      nodePort: 30000 # The static port you want to expose on the node

